_target_: calvin.models.encoders.plan_recognition_net.PlanRecognitionNetwork
visual_features: ???
plan_features: 256
action_space: ${datamodule.action_space}
birnn_dropout_p: 0.0
n_state_obs: ???
min_std: 0.0001
