_target_: calvin.datasets.npz_dataset.NpzDataset
key: "lang"
save_format: "npz"
batch_size: 32
min_window_size: 16
max_window_size: 32
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
skip_frames: 1
pad: true
lang_folder: "lang_annotations"
