_target_: calvin.datasets.disk_dataset.DiskDataset
key: "lang"
save_format: "pkl"
batch_size: 2
min_window_size: 32
max_window_size: 32
obs_space: ${observation_space}
proprio_state: ${proprioception_dims}
skip_frames: 32 #Two per annotation
pad: false
