_target_: calvin.models.encoders.plan_proposal_net.PlanProposalNetwork
visual_features: ???
latent_goal_features: 32
plan_features: 256
activation_function: ReLU #ELU
n_state_obs: ???
min_std: 0.0001
