defaults:
  - plan_proposal: default
  - plan_recognition: default
  - vision_static: default
  - vision_gripper: none
  - visual_goal: default
  - language_goal: none
  - decoder: logistic #(logistic, gaussian)
  - optimizer: adam
  - lr_scheduler: constant


_target_: calvin.models.play_lmp.PlayLMP
_recursive_: false

proprio_state: ${datamodule.proprioception_dims}
kl_beta: ${loss.kl_beta}
