_target_: vr_env.envs.tasks.Tasks
tasks:
  # rotation
  rotate_banana_right: [rotate_object, 'banana', -60]
  rotate_banana_left: [rotate_object, 'banana', 60]
  rotate_salt_right: [rotate_object, 'salt', -60]
  rotate_salt_left: [rotate_object, 'salt', 60]

  # sliding
  slide_banana_right: [push_object, 'banana', 0.1, 0]
  slide_bowl_right: [push_object, 'bowl', 0.1, 0]
  slide_bowl_left: [push_object, 'bowl', -0.1, 0]
  slide_salt_right: [push_object, 'salt', 0.1, 0]
  slide_salt_left: [push_object, 'salt', -0.1, 0]
  slide_thuna_right: [push_object, 'thuna', 0.1, 0]
  slide_thuna_left: [push_object, 'thuna', -0.1, 0]

  # open/close
  move_slider_left: [move_door_rel, 'table', 'slide_door_joint', 0.28]  # 0 - 0.56
  move_slider_right: [move_door_rel, 'table', 'slide_door_joint', -0.28]
  open_drawer: [move_door_rel, 'drawer', 'drawer_joint', 0.12]  # 0 - 0.24
  close_drawer: [move_door_rel, 'drawer', 'drawer_joint', -0.12]

  # lifting
  lift_banana_table: [lift_object, 'banana', 0.05, 'table', 'base_link']
  lift_bowl_table: [lift_object, 'bowl', 0.05, 'table', 'base_link']
  lift_salt_table: [lift_object, 'salt', 0.05, 'table', 'base_link']
  lift_thuna_table: [lift_object, 'thuna', 0.05, 'table', 'base_link']
  lift_thuna_drawer: [lift_object, 'thuna', 0.05, 'drawer']
  grasp_bowl_left_shelf: [lift_object, 'bowl', 0.05, 'table', 'bottom_left_table']
  grasp_salt_right_shelf: [lift_object, 'salt', 0.02, 'table', 'bottom_right_table']
