_target_: lfp.models.encoders.goal_encoders.VisualGoalEncoder
visual_features: ???
hidden_size: 2048
latent_goal_features: 32
l2_normalize_goal_embeddings: False
activation_function: ReLU #ELU
n_state_obs: ???
